# SPDX-FileCopyrightText: 2020-2021 Stephan Lachnit <stephanlachnit@protonmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Build and test
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          sudo apt install meson gettext appstream flake8 pylint python3-enchant aspell desktop-file-utils
      - name: Build and install
        run: |
          meson builddir
          ninja -C builddir
          sudo ninja install -C builddir
      - name: Run tests
        run: |
          ninja test -C builddir
      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            builddir/meson-logs/
